import React from 'react'

export default function About() {
    return (
        <div >
            <h1 className='text-5xl'>About</h1>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita debitis odit tempore id, labore quidem. Blanditiis nostrum sapiente, deserunt voluptate facilis aliquid, sint nesciunt minus labore odio necessitatibus, mollitia velit? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque explicabo assumenda doloremque eveniet dicta quisquam ipsam maxime esse sint sunt maiores, molestias omnis qui magni! Consequuntur numquam excepturi harum enim? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum quaerat quam fugiat assumenda quisquam. Quas perferendis nulla ducimus nisi hic expedita eum fuga doloribus. Incidunt blanditiis nulla sed modi non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus odio suscipit culpa doloribus. Qui quisquam incidunt non atque deleniti dolores nobis debitis tenetur quaerat hic. Nobis omnis repudiandae exercitationem cupiditate?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita debitis odit tempore id, labore quidem. Blanditiis nostrum sapiente, deserunt voluptate facilis aliquid, sint nesciunt minus labore odio necessitatibus, mollitia velit? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque explicabo assumenda doloremque eveniet dicta quisquam ipsam maxime esse sint sunt maiores, molestias omnis qui magni! Consequuntur numquam excepturi harum enim? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum quaerat quam fugiat assumenda quisquam. Quas perferendis nulla ducimus nisi hic expedita eum fuga doloribus. Incidunt blanditiis nulla sed modi non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus odio suscipit culpa doloribus. Qui quisquam incidunt non atque deleniti dolores nobis debitis tenetur quaerat hic. Nobis omnis repudiandae exercitationem cupiditate?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita debitis odit tempore id, labore quidem. Blanditiis nostrum sapiente, deserunt voluptate facilis aliquid, sint nesciunt minus labore odio necessitatibus, mollitia velit? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque explicabo assumenda doloremque eveniet dicta quisquam ipsam maxime esse sint sunt maiores, molestias omnis qui magni! Consequuntur numquam excepturi harum enim? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum quaerat quam fugiat assumenda quisquam. Quas perferendis nulla ducimus nisi hic expedita eum fuga doloribus. Incidunt blanditiis nulla sed modi non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus odio suscipit culpa doloribus. Qui quisquam incidunt non atque deleniti dolores nobis debitis tenetur quaerat hic. Nobis omnis repudiandae exercitationem cupiditate?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita debitis odit tempore id, labore quidem. Blanditiis nostrum sapiente, deserunt voluptate facilis aliquid, sint nesciunt minus labore odio necessitatibus, mollitia velit? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque explicabo assumenda doloremque eveniet dicta quisquam ipsam maxime esse sint sunt maiores, molestias omnis qui magni! Consequuntur numquam excepturi harum enim? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum quaerat quam fugiat assumenda quisquam. Quas perferendis nulla ducimus nisi hic expedita eum fuga doloribus. Incidunt blanditiis nulla sed modi non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus odio suscipit culpa doloribus. Qui quisquam incidunt non atque deleniti dolores nobis debitis tenetur quaerat hic. Nobis omnis repudiandae exercitationem cupiditate?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita debitis odit tempore id, labore quidem. Blanditiis nostrum sapiente, deserunt voluptate facilis aliquid, sint nesciunt minus labore odio necessitatibus, mollitia velit? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque explicabo assumenda doloremque eveniet dicta quisquam ipsam maxime esse sint sunt maiores, molestias omnis qui magni! Consequuntur numquam excepturi harum enim? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum quaerat quam fugiat assumenda quisquam. Quas perferendis nulla ducimus nisi hic expedita eum fuga doloribus. Incidunt blanditiis nulla sed modi non. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus odio suscipit culpa doloribus. Qui quisquam incidunt non atque deleniti dolores nobis debitis tenetur quaerat hic. Nobis omnis repudiandae exercitationem cupiditate?</p>
        </div>
    )
}
